### PR TITLE
Add method to ConfigurationManipulator to output parameter tree [codereview?]

### PR DESCRIPTION
**Pull request by Sierangho**
added "serialize_parameters" method. Not sure about the naming for the method.

### CODE REVIEW

**Comment by jansel** [comment]
Maybe tweak the format a bit an make this either the __repr__ or __str__ method?

**Comment by Sierangho** [comment]
I can make it the __str__ method then? 

According to standards, __repr__ should be completely unambiguous so eval(repr(manipulator)) should get you an identical object. This isn't quite the case since I don't track the parameter.name values.

**Comment by Sierangho** [comment]
Did you have suggestions for a better output format? I was just trying to get something easily parseable to compare parameter trees used by tuning programs.

**Comment by jansel** [comment]
Why not just compare the trees directly as objects without serializing?  If you want to use json, I would construct a tree in memory then json.dumps the tree.  For serializing/de-serializing I would use pickle.

**Comment by Sierangho** [comment]
I wanted a way to save the representation (defined by the parameter tree) of a problem in the global database to be able to compare representations later. 

I don't think I want a direct dump of the manipulator, as the same parameter type might have different names defined by a user (i.e. IntegerParameter x, y with x.name = foo and y.name = bar). However, in terms of a representation for a problem, all IntegerParameters should be the same. Also, the order of the parameters shouldn't matter. 

I guess I don't actually want serialization either since we wouldn't need to reconstruct the manipulator.

**Comment by Sierangho** [comment]
I tried to change the method names to reflect the intent better (which is to get a json format for the parameters in a way so "equivalent" sets of parameters have the same output)

**Pull request merged**
