### PR TITLE
Python 3 support (using future)

### PR DESCRIPTION
**Pull request by leonidk**
See #103. This commit uses an automatic run of [python-future](http://python-future.org/#) to add python 3 compatibility, and using the future package in python2, this code should support both python2 and python3. I tested in Python 3.6 and Python 2.7 on Mac OS X through the current Anaconda python channels. 

I did a few manual changes in manipulator.py to allow hashing of the configurations by enabling encoding. 

In my brief testing it works fine with both (although the opentuner.db folder created in py36 contains pickle dumps of a newer version, so running the py27 version in that folder afterwards crashes)

### CODE REVIEW

**Comment by jbosboom** [comment]
I have a deadline on the 23rd so it will be a few days before I can look at this.

**Comment by jbosboom** [comment]
Scrolling through that big list of mechanical changes, all I can think is "why would Python do this to itself?"  That said, I'm not opposed to supporting Python 3 in principle, though I want @jansel's approval too.

If we take this (or #108), we do need some kind of CI infrastructure to ensure changes don't break things for the other version.  OpenTuner doesn't have tests in the traditional sense, but we could set up a bot that runs some of the examples under various bandits and ensures they make some progress, which would at least ensure there are no syntax or egregious semantic errors in the covered code.  (Testing correctness is a bit more difficult; we've had some bugs in techniques that were masked by the bandit just choosing other techniques.)

**Comment by jansel** [comment]
Sorry, somehow I missed this when it was submitted.  Seems reasonable.  Thanks!

**Comment by leonidk** [comment]
@jansel I think #108 is probably simpler/better as it doesn't require installing a new package (future). I think @jbosboom call for more testing is also reasonable, as a lot of semantics did change. I only did a handful of cursory tests.

**Comment by jansel** [comment]
I agree we need more testing.  Future is rather ubiquitous so I am not too worried about it.

**Comment by wangx173** [comment]
I did a bit testing with python3.6, 
Currently the following code is added for `PrimitiveParameter`
```python
    return hashlib.sha256(repr(self.get_value(config))).hexdigest()
    return hashlib.sha256(repr(self.get_value(config)).encode('utf-8')).hexdigest().encode('utf-8')
```

and the same thing needs to be done for `ComplexParameter`, otherwise it will cause some encoding issues when using `ComplexParameter`

**Pull request merged**
